server:
  port: 8081
  servlet:
    context-path: /redpacket

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: at least ${limit.minMoney} dollar, at most ${limit.maxMoney} dollars!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redpacket
    username: root
    password: '00000000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
